### PR TITLE
fix incompatible usage vs terraform v0.7

### PR DESCRIPTION
**Pull request by tamsky**
`security_groups` -> `vpc_security_group_ids`

per:  https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#070-august-2-2016

### CODE REVIEW

**Comment by tamsky** [comment]
Callers of this module will require the same name change on the calling side.

**Comment by antonbabenko** [comment]
According to the [documentation](https://www.terraform.io/docs/providers/aws/r/instance.html) it says:

```
security_groups - (Optional) A list of security group names to associate with. If you are creating Instances in a VPC, use vpc_security_group_ids instead.
vpc_security_group_ids - (Optional) A list of security group IDs to associate with.
```

I am not sure that the proposed change is required. Can someone maybe try it also ?

**Comment by ashb** [comment]
@antonbabenko this change looks good to me btw.

**Comment by antonbabenko** [comment]
Double quotes should not be escaped, I believe. This is related to all places where interpolation is used.

**Comment by ashb** [comment]
I've got another PR waiting that will fix all that up - but it relies on this change first. I can fold in this commit (maintaining original author) if you'd like.

**Comment by antonbabenko** [comment]
Ok, merged now.

**Pull request merged**
