### PR TITLE
Upgrade to support new v0.12 HCL Syntax

### PR DESCRIPTION
**Pull request by DomWeldon**
Altered syntax such that it will no longer cause errors in Terraform 0.12.

### CODE REVIEW

**Comment by mgfinch** [comment]
Thanks, it looks good. Why is it not accepted yet?

**Review by Dzhuneyt — APPROVED** [review]
Changes sound good to me. This closes #22

**Comment by Adam-Randall** [comment]
Any idea when this is getting merged? 👍

**Comment by antonbabenko** [comment]
I can merge it now, but please be aware that this module has not been really tested or maintained for the last 3 years.

**Comment by antonbabenko** [comment]
[v1.4.0](https://github.com/terraform-community-modules/tf_aws_nat/releases/v1.4.0) has been just released.

**Pull request merged**
